"""Model comparison analysis for adaptation experiments.

This script consumes the exports generated by :mod:`cst_run_generalization.py` and
produces a small set of figures/tables that compare representative RNN and
NeuraGEM configurations across the three experiment suites (OOD stds, OOD
means, and block-size sweeps).  The previous ad-hoc script has been refactored
to:

* share experiment metadata with ``cst_run_generalization.py`` so the analysis stays in
  sync with the executed sweeps,
* tolerate missing runs gracefully while still reporting which artefacts were
  found,
* run every experiment suite in a single invocation, and
* encapsulate plotting/statistical routines so they are easier to extend for
  publication-ready figures.

The heavy numerical work (e.g. computing peri-switch errors) remains in the
utility modules.  This file orchestrates loading, aggregation, plotting, and
optional statistical tests.
"""

from __future__ import annotations
try:  # safer IPython auto-reload setup
    from IPython import get_ipython  # type: ignore
    _ip = get_ipython()
    if _ip is not None:
        _ip.run_line_magic('load_ext', 'autoreload')
        _ip.run_line_magic('autoreload', '2')
except Exception:
    pass

from pathlib import Path

from cst_analyze_gen_tests_utils import (
    AnalysisParams,
    ComparisonSpec,
    RunSpec,
    gather_payloads,
    plot_test_summary,
    summarise_test_loggers,
)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


DEFAULT_EXPORT_ROOT = Path("./exports/contextual_switching_task/experiments")


RUN_SPECS = {
    "new_runs_stds": RunSpec(
        run_name="new_runs_50_stds",
        ood_test_type="ood_stds",
        iid_reference_values=(0.3,),
        comparisons=(
            ComparisonSpec(
                key="default_std_0p3_with_neuragem",
                title="Observation noise sweep",
                model_overrides={
                    "rnn_seq_len_5": {"default_std": 0.3},
                    "rnn_seq_len_50": {"default_std": 0.3},
                    "neuragem": {"default_std": 0.3, "l2_loss": 0.0001},
                    "bayesian": {"default_std": 0.3, "observation_noise_mode": {"default": "fixed", "ood_stds": "fixed"}},
                },
                primary_compare=("rnn_seq_len_50", "neuragem"),
            ),
            ComparisonSpec(
                key="default_std_0p3_rnns_only",
                title="Observation noise sweep",
                model_overrides={
                    "rnn_seq_len_5": {"default_std": 0.3},
                    "rnn_seq_len_50": {"default_std": 0.3},
                    "bayesian": {"default_std": 0.3, "observation_noise_mode": {"default": "fixed", "ood_stds": "fixed"}},
                },
                primary_compare=("rnn_seq_len_5", "rnn_seq_len_50"),
            ),
        ),
    ),
    "new_runs_means": RunSpec(
        # run_name="new_runs_means",
        run_name="new_runs_50_means",
        ood_test_type="ood_means",
        iid_reference_values=(0.2, 0.8),
        comparisons=(
            ComparisonSpec(
                key="default_std_0p3",
                title="OOD means (std 0.3)",
                model_overrides={
                    "rnn_seq_len_5": {"default_std": 0.3},
                    "rnn_seq_len_50": {"default_std": 0.3},
                    # "neuragem": {"default_std": 0.3, "l2_loss": 0.0008},
                    # "bayesian": {"default_std": 0.3},
                },
                primary_compare=("rnn_seq_len_5", "rnn_seq_len_50"),
            ),
            ComparisonSpec(
                key="default_std_0p3_neuragem_l2_0p0008",
                title="OOD means (std 0.3)",
                model_overrides={
                    "rnn_seq_len_5": {"default_std": 0.3},
                    "rnn_seq_len_50": {"default_std": 0.3},
                    "neuragem": {"default_std": 0.3, "l2_loss": 0.0008},
                    # "bayesian": {"default_std": 0.3},
                },
                primary_compare=("rnn_seq_len_50", "neuragem"),
            ),
        ),
    ),
    "new_runs_50_block_size": RunSpec(
        run_name="new_runs_50_block_size",
        ood_test_type="block_size",
        iid_reference_values=(25,),
        comparisons=(
            # ComparisonSpec(
            #     key="default_std_0p3",
            #     title="Block-size sweep (std 0.3)",
            #     model_overrides={
            #         "rnn_seq_len_5": {"default_std": 0.3},
            #         "rnn_seq_len_50": {"default_std": 0.3},
            #         "neuragem": {"default_std": 0.3, "l2_loss": 0.0001},
            #         "bayesian": {"default_std": 0.3},
            #     },
            # ),
            ComparisonSpec(
                key="default_std_0p4_rnns_only",
                title="Block-size sweep (std 0.4)",
                model_overrides={
                    "rnn_seq_len_5": {"default_std": 0.4},
                    "rnn_seq_len_50": {"default_std": 0.4},
                    # "neuragem": {"default_std": 0.4, "l2_loss": 0.0001},
                    # "bayesian": {"default_std": 0.4},
                },
                primary_compare=("rnn_seq_len_5", "rnn_seq_len_50"),
            ),
            ComparisonSpec(
                key="default_std_0p4_with_neuragem",
                title="Block-size sweep (std 0.4)",
                model_overrides={
                    "rnn_seq_len_5": {"default_std": 0.4},
                    "rnn_seq_len_50": {"default_std": 0.4},
                    "neuragem": {"default_std": 0.4, "l2_loss": 0.0001},
                    # "bayesian": {"default_std": 0.4},
                },
                primary_compare=("rnn_seq_len_50", "neuragem"),
            ),
        ),
    ),
}
# temp remove other runs for debugging
# RUN_SPECS.pop('new_runs_stds')
# RUN_SPECS.pop('new_runs_means')
# RUN_SPECS.pop('new_runs_block_size')


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def process_comparison(
    run_spec: RunSpec,
    comparison: ComparisonSpec,
    export_root: Path,
    params: AnalysisParams,
) -> None:
    analysis_dir = export_root / run_spec.run_name / "model_comparison" / comparison.key
    analysis_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nProcessing {run_spec.run_name} - {comparison.key}")
    payloads = gather_payloads(run_spec, comparison, export_root, params)
    if not any(payloads.values()):
        print("  No payloads found; skipping comparison.")
        return

    summary = summarise_test_loggers(run_spec, comparison.key, payloads, params)
    if not any(summary.values()):
        print("  No test loggers summarised; skipping test plot.")
        return
    plot_test_summary(run_spec, comparison, summary, params, analysis_dir)


def main() -> None:
    params = AnalysisParams()
    export_root = DEFAULT_EXPORT_ROOT

    for run_key, run_spec in RUN_SPECS.items():
        run_path = export_root / run_spec.run_name
        if not run_path.exists():
            print(f"Run directory not found for {run_spec.run_name}; continuing with available models.")
        for comparison in run_spec.comparisons:
            process_comparison(run_spec, comparison, export_root, params)


if __name__ == "__main__":
    main()
